### ISSUE TITLE
Ignore patches in the farming guild for the other groups (e.g. herbs)

### ISSUE THREAD

**Issue by gpis0time** [queicherius/runelite-time-tracking-reminder#22]
Add option to split farming guild from groups (cactus,herb, ... ,tree)

**Comment by Equilities** [comment]
Would love this, currently herb notifier isn't really useful most of the time due to this issue due to the prevalence of pre-planting farming guild for contracts. If prefer soonest completion is checked, then it will say your herb run is ready when only your farming guild one is. If it's not checked, then it won't say your herb run is ready unless your farming guild one is also ready. It'd be quite useful if we could detach farming guild entirely.

**Comment by OilyHands** [comment]
Came here to request this. Would be very neat

**Comment by jazztothetwo** [comment]
"Prefer soonest completion" Does somewhat alleviate the issue. However you then get the issue that the plugin will falsely report "Your fruit tree patches are ready!" When only the Celastrus is ready. 
An "Ignore farming guild" solve this.
Or secondly, how "Trees" and "Hardwood Trees" are separate check boxes, separating Celastrus from "Fruit trees" would also solve the issue.  This would also bring fruit trees in line with the rest of the timers. That is, how trees/hardwood trees/redwood trees are different options.
